services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=catalog'
      # I know this is cursed, but this is a stupid university project, so I don't care
      # FIXME: replace with a proper secret management solution
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
